### ISSUE TITLE
I can't find 'tracetools_analysis'

### ISSUE THREAD

**Issue by minlingji** [hsgwa/e2e_demo#1]
1.I running e2e.launch.py
2.running jupyter notebook
3.running e2e_latency.ipynb
4.ptint error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-94af3e5a4592> in <module>
----> 1 from tracetools_analysis.ros_model import ApplicationFactory

ModuleNotFoundError: No module named 'tracetools_analysis'

I don't know why

**Comment by hsgwa** [comment]
Thanks for the comment!
I'm sorry that the documents aren't well-developed yet.

If you follow the steps as described here, it should work.
https://github.com/azu-lab/ROS2-E2E-Evaluation

To find tracetools_analysis from python, you need to run setup.bash in ros2_fork_foxy like as follows.
```
$ . ~/ros2_foxy_fork/install/setup.bash
$ jupyter-lab
```

Could you please share the outputs of the following command?
```
$ . ~/ros2_foxy_fork/install/setup.bash
$ echo $PYTHONPATH | tr : '\n' | grep tracetools_analysis
/home/user_name/ros2_foxy_fork/build/tracetools_analysis
/home/user_name/ros2_foxy_fork/install/tracetools_analysis/lib/python3.8/site-packages
```

**Comment by minlingji** [comment]
> Thanks for the comment!
> I'm sorry that the documents aren't well-developed yet.
> 
> If you follow the steps as described here, it should work.
> https://github.com/azu-lab/ROS2-E2E-Evaluation
> 
> To find tracetools_analysis from python, you need to run setup.bash in ros2_fork_foxy like as follows.
> 
> ```
> $ . ~/ros2_foxy_fork/install/setup.bash
> $ jupyter-lab
> ```
> 
> Could you please share the outputs of the following command?
> 
> ```
> $ . ~/ros2_foxy_fork/install/setup.bash
> $ echo $PYTHONPATH | tr : '\n' | grep tracetools_analysis
> /home/user_name/ros2_foxy_fork/build/tracetools_analysis
> /home/user_name/ros2_foxy_fork/install/tracetools_analysis/lib/python3.8/site-packages
> ```

thanks for your reply
I found my error!
I try git clone https://gitlab.com/HasegawaAtsushi/tracetools_analysis.git -b devel_e2e_measurement
yesterday this tracetools_analysis is from https://gitlab.com/ros-tracing/tracetools_analysis -b master

**Comment by hsgwa** [comment]
The error seems to have been resolved, so I'm closing this issue.
Please ask me if you need anything else.
