### ISSUE TITLE
[QST]the callback dependency cannot be auto-generated.

### ISSUE THREAD

**Issue by ZhenshengLee** [hsgwa/e2e_demo#2]
I've read the paper of your team, that's a wonderful work!
I tried to reproduce the behavior of this demo in galactic branch, and find that the generated arch.json.temp is different from the original one in the repo, which means the python scripts of e2e trace may behave abnormal.

## Env

- Ubuntu 20.04
- ROS2(galactic) compiled with the following branch based on your repo https://github.com/azu-lab/ROS2-E2E-Evaluation
https://github.com/ZhenshengLee/ros2_tracing
https://github.com/ZhenshengLee/tracetools_analysis
https://github.com/ros2middleware/rclcpp
https://github.com/ros2middleware/rcl
https://github.com/ros2middleware/rmw_cyclonedds
https://github.com/ros2middleware/cyclonedds
the branch of all is outdoor/galactic

## Steps 

```sh
trace_create_template ./e2e_demo ./arch_temp.json
```

## expected

the arch_temp.json is  the same with https://github.com/hsgwa/e2e_demo/blob/master/e2e_demo/analysis/architecture.json.template

## actual 

the first result is the galactic branch os the e2e demo repos
https://github.com/ros2middleware/e2e_demo/commit/115cb9c47532587e577d1b6fb1d3d0e4cdcf3963

the second result is when I added foxy branch of the repos 
https://github.com/ros2middleware/e2e_demo/commit/e7527ce876653422150a1acc294f29a025d2a34b

## question

Is this behavior abnormal?
Is anything I missed from https://github.com/azu-lab/ROS2-E2E-Evaluation/blob/main/autoware_perf_foxy/README.md
and https://github.com/azu-lab/ROS2-E2E-Evaluation/blob/main/autoware_perf_galactic/README.md

Thanks!

**Comment by hsgwa** [comment]
@ZhenshengLee 

Sorry for the late reply.
We have now finished the development of Autoware_perf and renamed it as CARET.
Autoware_perf used to fork ros source code to add tracepoints, but CARET uses LD_PRELOAD hooks to add tracepoints.

You can find the documentation here.
https://tier4.github.io/CARET_doc/latest/

If you have any questions, I would appreciate it if you could give them to this issue.
https://github.com/tier4/CARET

**Comment by ZhenshengLee** [comment]
> We have now finished the development of Autoware_perf and renamed it as CARET.

Glad to see that! 

Closing this.
